# Generated by Django 5.2.1 on 2025-06-05 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_category_achievement_community_goal_activity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('', 'Здоровье'), ('', 'Финансы'), ('', 'Карьера'), ('', 'Саморазвитие'), ('', 'Духовность'), ('', 'Отдых'), ('', 'Отношения'), ('', 'Семья')], max_length=255, unique=True, verbose_name='Название категории'),
        ),
    ]
