# Generated by Django 5.2.1 on 2025-06-05 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('Health', 'Здоровье'), ('Finance', 'Финансы'), ('Career', 'Карьера'), ('Self-development', 'Саморазвитие'), ('Spirituality', 'Духовность'), ('Reset', 'Отдых'), ('Relationship', 'Отношения'), ('Family', 'Семья')], max_length=255, unique=True, verbose_name='Название категории'),
        ),
    ]
