# Generated by Django 5.2.1 on 2025-06-05 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
