# Generated by Django 5.2.1 on 2025-06-05 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_activity_end_time_activity_start_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='start_time',
        ),
    ]
