# Generated by Django 5.2.1 on 2025-06-05 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_activity_end_time_remove_activity_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='activity',
            field=models.CharField(max_length=100, null=True, verbose_name='Активность'),
        ),
    ]
