# Generated by Django 5.2.1 on 2025-06-05 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_activity_activity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['start_time'], 'verbose_name': 'Действие', 'verbose_name_plural': 'Действия'},
        ),
        migrations.RemoveField(
            model_name='activity',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='activity',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='name',
            field=models.CharField(max_length=255, null=True, verbose_name='Название достижения'),
        ),
        migrations.AddField(
            model_name='activity',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
