# Generated by Django 5.2.1 on 2025-06-05 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_activity_options_remove_activity_activity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='name',
            field=models.CharField(max_length=255, null=True, verbose_name='Название действия'),
        ),
    ]
