# Generated by Django 5.2.1 on 2025-06-10 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_activity_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='color',
            field=models.CharField(default='#CCCCC', max_length=7, verbose_name='Цвет категории'),
        ),
    ]
