# Generated by Django 5.2.1 on 2025-06-11 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_category_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='category',
        ),
    ]
