# Generated by Django 5.2.1 on 2025-06-11 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_activity_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='category',
        ),
    ]
