# Generated by Django 5.2.1 on 2025-06-15 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_activity_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='habit',
            old_name='activiti',
            new_name='activities',
        ),
    ]
