# Generated by Django 5.2.1 on 2025-06-16 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_rename_activiti_habit_activities'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='period',
            field=models.CharField(choices=[('day', 'В день'), ('week', 'В неделю'), ('month', 'В месяц')], default='day', max_length=10, verbose_name='Период'),
        ),
    ]
