# Generated by Django 5.2.1 on 2025-06-16 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_goal_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='name',
            field=models.CharField(db_index=True, max_length=255, null=True, verbose_name='Название цели'),
        ),
    ]
